GET http://localhost:3001/notes

###

POST http://localhost:3001/notes
content-type: application/json

{
      "createdAt": "2022-09-19T12:07:58.680Z",
      "author": "Michelle",
      "authorType": "Clinician",
      "text": "LOREM IPSUM"
}
